### ISSUE TITLE
[Unity]: Unity theme broken

### ISSUE THREAD

**Issue by JellyBrick** [joshuah345/Discord-Stuff#2]
**Describe the bug**
`Unity.css` no longer works, because `Discord` has renamed CSS classes.

**To Reproduce**
1. Apply `Unity`.

**Expected behavior**
`Unity.css` should be applied normally.

**Screenshots**
_No Response_

**Additional context**
_No Response_

**Comment by joshuah345** [comment]
3b4843879a804dc7c9130953607e1780e3b8af83 fixes this
